name: "deadnix"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
        with:
          flags: "-l"
