name: "deadnix"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - uses: astro/deadnix-action@main
        with:
          flags: "-l"
