name: "deadnix"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v33

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - uses: astro/deadnix-action@main
        with:
          flags: "-l"
